{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/orionking12/VITALIS-PRIME-THE-CONVERGENT-INTELLIGENCE-KERNEL-V.99-/blob/main/Suite_Vitalis_Prime.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>\n",
        "\n",
        "# VITALIS-PRIME: The Convergent Intelligence Kernel (v1.0)\n",
        "\n",
        "**Crónica de una Evolución Arquitectónica**\n",
        "\n",
        "Este documento resume el proceso de ingeniería liderado por **Jorge Humberto Davalos Gonzalez** para crear un sistema de inteligencia neuro-híbrida capaz de sobrevivir a colapsos cuánticos y derivas de concepto (*Concept Drift*).\n",
        "\n",
        "### ¿Para qué sirve Vitalis-Prime?\n",
        "Vitalis-Prime es un Gemelo Digital Evolutivo. Su propósito no es solo monitorear, sino sobrevivir y adaptarse a entornos donde las reglas cambian dinámicamente.\n",
        "\n",
        "* **Resiliencia ante el Caos:** Si una anomalía engaña a los modelos clásicos, la red neuronal toma el control automáticamente.\n",
        "* **Observabilidad Cognitiva:** Permite \"ver\" la mente de la IA a través del Holoscopio 3D, visualizando la tensión entre modelos como fuerzas gravitacionales.\n",
        "* **Aprendizaje Autónomo:** El sistema se reentrena solo, usando ventanas de \"amnesia estructurada\" para olvidar datos obsoletos y aprender las nuevas leyes del entorno.\n",
        "\n",
        "---\n",
        "👤 **Información del Autor**\n",
        "* **Desarrollador:** Jorge Humberto Davalos Gonzalez\n",
        "* **Contacto:** luckystrike@gmail.com\n",
        "* **Ubicación:** Guadalajara, Jal., México.\n",
        "* **Licencia:** MIT. Disponible para comercialización e implementación personalizada."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "install-dependencies"
      },
      "source": [
        "# Instalación de dependencias requeridas para el ecosistema\n",
        "!pip install -q dash plotly nest-asyncio flask torch scikit-learn pandas requests aiohttp"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "architecture-docs"
      },
      "source": [
        "## 🏗️ Arquitectura del Sistema\n",
        "\n",
        "El ecosistema se divide en módulos independientes que operan en paralelo:\n",
        "\n",
        "1. **El Núcleo de Inteligencia (`servidor_nucleo.py`)**\n",
        "   Es el cerebro del sistema. Implementa un Sincronizador Neuro-Híbrido con Ingesta asíncrona (Flask), Mecanismo de atención atencional y un marco de Pérdida dual (*Dual Loss*).\n",
        "2. **El Holoscopio de Resonancia Cognitiva**\n",
        "   La interfaz de observabilidad 3D. Traduce métricas abstractas en física visual (Atractores gravitacionales y el Océano de Pérdida).\n",
        "3. **El Enjambre Adversario (`enjambre_adversario.py`)**\n",
        "   Un orquestador de pruebas de estrés diseñado para simular el colapso de las leyes físicas y forzar la re-evolución de la inteligencia."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "core-system"
      },
      "source": [
        "import os\n",
        "import sys\n",
        "import time\n",
        "import uuid\n",
        "import threading\n",
        "import queue\n",
        "import argparse\n",
        "import random\n",
        "import math\n",
        "import asyncio\n",
        "from collections import deque\n",
        "from datetime import datetime\n",
        "\n",
        "# Dependencias Externas\n",
        "import numpy as np\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.optim as optim\n",
        "import requests\n",
        "import aiohttp\n",
        "from flask import Flask, request, jsonify\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "\n",
        "# Importaciones para el Holoscopio (Dashboard)\n",
        "try:\n",
        "    import dash\n",
        "    from dash import dcc, html\n",
        "    from dash.dependencies import Input, Output\n",
        "    import plotly.graph_objs as go\n",
        "except ImportError:\n",
        "    print(\"Nota: Para ejecutar el modo 'holoscopio', instala: pip install dash plotly\")\n",
        "\n",
        "# =====================================================================\n",
        "# 1. NÚCLEO NEURO-HÍBRIDO (ARQUITECTURA DE PRODUCCIÓN)\n",
        "# =====================================================================\n",
        "\n",
        "class AdvancedGenerator(nn.Module):\n",
        "    \"\"\"Generador con extracción de representaciones latentes y Logits puros.\"\"\"\n",
        "    def __init__(self, input_dim, latent_dim, output_dim):\n",
        "        super().__init__()\n",
        "        self.encoder = nn.Sequential(\n",
        "            nn.Linear(input_dim, 128), nn.ReLU(),\n",
        "            nn.Linear(128, latent_dim), nn.ReLU()\n",
        "        )\n",
        "        self.decoder = nn.Sequential(\n",
        "            nn.Linear(latent_dim, 64), nn.ReLU(),\n",
        "            nn.Linear(64, output_dim)\n",
        "        )\n",
        "    def forward(self, x):\n",
        "        latent = self.encoder(x)\n",
        "        logits = self.decoder(latent)\n",
        "        return logits, latent\n",
        "\n",
        "class LatentTransformer(nn.Module):\n",
        "    \"\"\"Transformador adaptativo para alinear latentes con espacio clásico.\"\"\"\n",
        "    def __init__(self, latent_dim, transformed_dim):\n",
        "        super().__init__()\n",
        "        self.transform = nn.Sequential(\n",
        "            nn.Linear(latent_dim, transformed_dim),\n",
        "            nn.LayerNorm(transformed_dim), nn.ReLU()\n",
        "        )\n",
        "    def forward(self, latent):\n",
        "        return self.transform(latent)\n",
        "\n",
        "class AttentionModule(nn.Module):\n",
        "    \"\"\"Módulo de atención y proyección final para la fusión de modelos.\"\"\"\n",
        "    def __init__(self, feature_dim, output_dim, n_models=2):\n",
        "        super().__init__()\n",
        "        self.attention = nn.Sequential(\n",
        "            nn.Linear(feature_dim * n_models, 64), nn.Tanh(),\n",
        "            nn.Linear(64, n_models), nn.Softmax(dim=1)\n",
        "        )\n",
        "        self.final_projection = nn.Linear(feature_dim, output_dim)\n",
        "\n",
        "    def forward(self, features):\n",
        "        combined = features.view(features.size(0), -1)\n",
        "        weights = self.attention(combined)\n",
        "        weighted_features = (features * weights.unsqueeze(2)).sum(dim=1)\n",
        "        final_logits = self.final_projection(weighted_features)\n",
        "        return final_logits, weights\n",
        "\n",
        "class NeuroHybridSynchronizer:\n",
        "    \"\"\"Orquestador que sincroniza el aprendizaje neuronal y estadístico.\"\"\"\n",
        "    def __init__(self, input_dim, latent_dim, classical_dim, output_dim):\n",
        "        self.generator = AdvancedGenerator(input_dim, latent_dim, output_dim)\n",
        "        self.transformer = LatentTransformer(latent_dim, classical_dim)\n",
        "        self.classical_model = RandomForestClassifier(n_estimators=50, warm_start=True)\n",
        "        self.attention_module = AttentionModule(feature_dim=classical_dim, output_dim=output_dim)\n",
        "        self.scaler = StandardScaler()\n",
        "\n",
        "        self.optimizer = optim.Adam([\n",
        "            {'params': self.generator.parameters()},\n",
        "            {'params': self.transformer.parameters()},\n",
        "            {'params': self.attention_module.parameters()}\n",
        "        ], lr=0.005)\n",
        "        self.criterion = nn.CrossEntropyLoss()\n",
        "\n",
        "# =====================================================================\n",
        "# 2. MODO: SERVIDOR NÚCLEO (CEREBRO)\n",
        "# =====================================================================\n",
        "\n",
        "def run_server():\n",
        "    app = Flask(__name__)\n",
        "    import logging\n",
        "    log = logging.getLogger('werkzeug')\n",
        "    log.setLevel(logging.ERROR)\n",
        "\n",
        "    DIM_ENTRADA = 3\n",
        "    DIM_LATENTE = 8\n",
        "    DIM_CLASICA = 2\n",
        "    DIM_SALIDA = 2\n",
        "\n",
        "    sincronizador = NeuroHybridSynchronizer(DIM_ENTRADA, DIM_LATENTE, DIM_CLASICA, DIM_SALIDA)\n",
        "    cola_feedback = []\n",
        "    memoria_X = deque(maxlen=2000)\n",
        "    memoria_y = deque(maxlen=2000)\n",
        "\n",
        "    stats = {\n",
        "        'lotes': 0,\n",
        "        'atn_gen': 0.5,\n",
        "        'atn_rf': 0.5,\n",
        "        'loss': 0.0\n",
        "    }\n",
        "\n",
        "    @app.route('/api/v1/telemetria/feedback', methods=['POST'])\n",
        "    def feedback():\n",
        "        data = request.get_json(force=True, silent=True)\n",
        "        if not data: return jsonify({'error': 'Invalid'}), 400\n",
        "        cola_feedback.append(data)\n",
        "        return jsonify({'status': 'encolado'}), 202\n",
        "\n",
        "    @app.route('/api/v1/sistema/estado', methods=['GET'])\n",
        "    def estado():\n",
        "        return jsonify({\n",
        "            'cola_pendientes': len(cola_feedback),\n",
        "            'metricas_motor_hibrido': {\n",
        "                'lotes_procesados': stats['lotes'],\n",
        "                'atencion_promedio_gen': stats['atn_gen'],\n",
        "                'atencion_promedio_rf': stats['atn_rf'],\n",
        "                'loss_actual': stats['loss']\n",
        "            },\n",
        "            'memoria_historica_rf': len(memoria_X)\n",
        "        })\n",
        "\n",
        "    def worker():\n",
        "        print(\"[Núcleo] ⚙️ Sincronizador activado...\")\n",
        "        X_init = np.random.rand(10, DIM_ENTRADA)\n",
        "        y_init = np.random.randint(0, DIM_SALIDA, 10)\n",
        "        sincronizador.scaler.fit(X_init)\n",
        "        sincronizador.classical_model.fit(sincronizador.scaler.transform(X_init), y_init)\n",
        "\n",
        "        while True:\n",
        "            if len(cola_feedback) >= 64:\n",
        "                lote = cola_feedback[:64]\n",
        "                del cola_feedback[:64]\n",
        "\n",
        "                X_batch = [[i['metricas_internas'].get('temperatura_q', 0),\n",
        "                            i['metricas_internas'].get('entropia_shannon', 0),\n",
        "                            i['metricas_internas'].get('amplitud_base', 0)] for i in lote]\n",
        "                y_batch = [1 if i['resultado_real'] == 'colapso_estable' else 0 for i in lote]\n",
        "\n",
        "                X_np = np.array(X_batch, dtype=np.float32)\n",
        "                y_np = np.array(y_batch, dtype=np.int64)\n",
        "\n",
        "                memoria_X.extend(X_np)\n",
        "                memoria_y.extend(y_np)\n",
        "\n",
        "                if stats['lotes'] % 10 == 0:\n",
        "                    X_h = sincronizador.scaler.fit_transform(np.array(memoria_X))\n",
        "                    sincronizador.classical_model.fit(X_h, np.array(memoria_y))\n",
        "\n",
        "                X_t = torch.tensor(X_np)\n",
        "                y_t = torch.tensor(y_np)\n",
        "\n",
        "                probs_rf = sincronizador.classical_model.predict_proba(sincronizador.scaler.transform(X_np))\n",
        "                if probs_rf.shape[1] < DIM_SALIDA:\n",
        "                    probs_rf = np.pad(probs_rf, ((0,0), (0, DIM_SALIDA - probs_rf.shape[1])), mode='constant')\n",
        "\n",
        "                c_feats = torch.tensor(probs_rf, dtype=torch.float32)\n",
        "\n",
        "                sincronizador.generator.train()\n",
        "                sincronizador.attention_module.train()\n",
        "                sincronizador.optimizer.zero_grad()\n",
        "\n",
        "                logits_gen, latent = sincronizador.generator(X_t)\n",
        "                trans_latent = sincronizador.transformer(latent)\n",
        "\n",
        "                combined = torch.stack([trans_latent, c_feats], dim=1)\n",
        "                final_logits, attn_w = sincronizador.attention_module(combined)\n",
        "\n",
        "                loss = sincronizador.criterion(final_logits, y_t) + 0.4 * sincronizador.criterion(logits_gen, y_t)\n",
        "                loss.backward()\n",
        "                sincronizador.optimizer.step()\n",
        "\n",
        "                stats['loss'] = round(loss.item(), 4)\n",
        "                pesos = attn_w.detach().mean(axis=0).numpy()\n",
        "                stats['atn_gen'] = round(float(pesos[0]), 3)\n",
        "                stats['atn_rf'] = round(float(pesos[1]), 3)\n",
        "                stats['lotes'] += 1\n",
        "\n",
        "                print(f\"📊 Lote {stats['lotes']} | Loss: {stats['loss']} | Atn: GEN {stats['atn_gen']} / RF {stats['atn_rf']}\")\n",
        "            else:\n",
        "                time.sleep(0.5)\n",
        "\n",
        "    threading.Thread(target=worker, daemon=True).start()\n",
        "    print(\"🚀 Servidor Vitalis-Prime en puerto 5000...\")\n",
        "    app.run(port=5000, debug=False, host='0.0.0.0')\n",
        "\n",
        "# =====================================================================\n",
        "# 3. MODO: HOLOSCOPIO (VISUALIZACIÓN 3D)\n",
        "# =====================================================================\n",
        "\n",
        "def run_holoscope():\n",
        "    URL = \"http://127.0.0.1:5000/api/v1/sistema/estado\"\n",
        "    app = dash.Dash(__name__, title=\"Holoscopio Vitalis-Prime\")\n",
        "\n",
        "    app.layout = html.Div(style={'backgroundColor': '#050505', 'color': '#00ffcc', 'fontFamily': 'monospace', 'height': '100vh'}, children=[\n",
        "        html.H1(\"VITALIS-PRIME // HOLOSCOPIO 3D\", style={'textAlign': 'center', 'padding': '10px'}),\n",
        "        html.Div(id='hud', style={'position': 'absolute', 'top': '80px', 'left': '20px', 'zIndex': '10', 'background': 'rgba(0,10,10,0.8)', 'padding': '15px', 'border': '1px solid #00ffcc'}),\n",
        "        dcc.Graph(id='graph', style={'height': '80vh'}),\n",
        "        dcc.Interval(id='timer', interval=1000)\n",
        "    ])\n",
        "\n",
        "    mx, my = np.meshgrid(np.linspace(-5, 5, 40), np.linspace(-5, 5, 40))\n",
        "\n",
        "    @app.callback([Output('graph', 'figure'), Output('hud', 'children')], [Input('timer', 'n_intervals')])\n",
        "    def update(n):\n",
        "        try:\n",
        "            r = requests.get(URL, timeout=1).json()\n",
        "            m = r['metricas_motor_hibrido']\n",
        "            at_g, at_r, loss, lotes = m['atencion_promedio_gen'], m['atencion_promedio_rf'], m['loss_actual'], m['lotes_procesados']\n",
        "        except:\n",
        "            at_g, at_r, loss, lotes = 0.5, 0.5, 0.05, 0\n",
        "\n",
        "        pos_g, pos_r = np.array([0, 3, 2]), np.array([0, -3, 2])\n",
        "        pos_p = pos_r + (pos_g - pos_r) * at_g\n",
        "        z_mesh = np.sin(mx + time.time()) * np.cos(my + time.time()) * (loss * 2)\n",
        "\n",
        "        fig = go.Figure(data=[\n",
        "            go.Scatter3d(x=[pos_g[0]], y=[pos_g[1]], z=[pos_g[2]], name=\"GEN\", marker=dict(size=10, color='#00aaff')),\n",
        "            go.Scatter3d(x=[pos_r[0]], y=[pos_r[1]], z=[pos_r[2]], name=\"RF\", marker=dict(size=10, color='#ffaa00')),\n",
        "            go.Scatter3d(x=[pos_p[0]], y=[pos_p[1]], z=[pos_p[2]], name=\"ESTADO\", marker=dict(size=8, color='white', symbol='cross')),\n",
        "            go.Surface(x=mx, y=my, z=z_mesh, colorscale='GnBu', opacity=0.5, showscale=False)\n",
        "        ])\n",
        "        fig.update_layout(scene=dict(xaxis=dict(visible=False), yaxis=dict(visible=False), zaxis=dict(visible=False), bgcolor='#050505'), margin=dict(l=0,r=0,b=0,t=0), paper_bgcolor='#050505')\n",
        "\n",
        "        hud = [html.P(f\"LOTES: {lotes}\"), html.P(f\"ATN NEURONAL: {at_g*100:.1f}%\"), html.P(f\"ATN CLÁSICA: {at_r*100:.1f}%\"), html.P(f\"LOSS: {loss:.4f}\", style={'color': 'red' if loss > 0.8 else '#00ffcc'})]\n",
        "        return fig, hud\n",
        "\n",
        "    print(\"🌌 Holoscopio en http://127.0.0.1:8050\")\n",
        "    app.run_server(port=8050, debug=False)\n",
        "\n",
        "# =====================================================================\n",
        "# 4. MODO: ENJAMBRE ADVERSARIO (CLIENTE DE ESTRÉS)\n",
        "# =====================================================================\n",
        "\n",
        "async def run_swarm():\n",
        "    URL = \"http://127.0.0.1:5000/api/v1/telemetria/feedback\"\n",
        "    print(\"☢️ Iniciando Enjambre Adversario...\")\n",
        "\n",
        "    async def send(session, ronda):\n",
        "        t, e, a = round(random.uniform(0.5, 10.0), 2), round(random.uniform(0.1, 5.0), 3), round(random.uniform(0.1, 1.0), 4)\n",
        "        if 7 <= ronda <= 13:\n",
        "            res = \"fallo_critico\" if (t < 4.0 and e < 2.0) else \"colapso_estable\"\n",
        "        else:\n",
        "            res = \"fallo_critico\" if (t > 7.0 or e > 3.5) else \"colapso_estable\"\n",
        "\n",
        "        payload = {\"metricas_internas\": {\"temperatura_q\": t, \"entropia_shannon\": e, \"amplitud_base\": a}, \"resultado_real\": res}\n",
        "        try:\n",
        "            async with session.post(URL, json=payload) as r: return r.status == 202\n",
        "        except: return False\n",
        "\n",
        "    async with aiohttp.ClientSession() as session:\n",
        "        for r in range(1, 21):\n",
        "            print(f\"--- Ronda {r}/20 ---\")\n",
        "            tasks = [send(session, r) for _ in range(150)]\n",
        "            await asyncio.gather(*tasks)\n",
        "            await asyncio.sleep(1.5)\n",
        "    print(\"🏁 Protocolo finalizado.\")\n",
        "\n",
        "# =====================================================================\n",
        "# PUNTO DE ENTRADA UNIFICADO\n",
        "# =====================================================================\n",
        "\n",
        "def execute_mode(mode):\n",
        "    if mode == \"servidor\":\n",
        "        run_server()\n",
        "    elif mode == \"holoscopio\":\n",
        "        run_holoscope()\n",
        "    elif mode == \"enjambre\":\n",
        "        import nest_asyncio\n",
        "        nest_asyncio.apply()\n",
        "        if sys.platform == 'win32':\n",
        "            asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())\n",
        "        asyncio.run(run_swarm())\n",
        "\n",
        "# Uso en terminal: des-comentar para ejecutar como script nativo.\n",
        "# if __name__ == \"__main__\":\n",
        "#     parser = argparse.ArgumentParser(description=\"Suite Vitalis-Prime Unificada\")\n",
        "#     parser.add_argument(\"mode\", choices=[\"servidor\", \"holoscopio\", \"enjambre\"], help=\"Selecciona componente\")\n",
        "#     args = parser.parse_args()\n",
        "#     execute_mode(args.mode)\n"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "infrastructure-gen-docs"
      },
      "source": [
        "## ⚙️ Generación de Infraestructura para Producción\n",
        "\n",
        "Ejecuta la siguiente celda para que el propio Notebook autogenere los archivos necesarios (`requirements.txt`, `Dockerfile`, y `run_prod.sh`) para desplegar este núcleo en la nube (ej. Render, Railway o AWS)."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "infrastructure-generator"
      },
      "source": [
        "import os\n",
        "\n",
        "# 1. Generar requirements.txt\n",
        "dependencies = ['flask', 'torch', 'scikit-learn', 'numpy', 'requests', 'aiohttp', 'nest-asyncio', 'dash', 'plotly', 'gunicorn']\n",
        "with open('requirements.txt', 'w') as f:\n",
        "    f.write('\\n'.join(dependencies) + '\\n')\n",
        "\n",
        "# 2. Generar Dockerfile (Multi-stage build para optimizar tamaño)\n",
        "dockerfile_content = r\"\"\"# Stage 1: Build stage\n",
        "FROM python:3.12-slim AS builder\n",
        "RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*\n",
        "WORKDIR /app\n",
        "COPY requirements.txt .\n",
        "RUN pip install --no-cache-dir --prefix=/install -r requirements.txt\n",
        "\n",
        "# Stage 2: Final runtime stage\n",
        "FROM python:3.12-slim\n",
        "WORKDIR /app\n",
        "COPY --from=builder /install /usr/local\n",
        "COPY . .\n",
        "EXPOSE 5000\n",
        "EXPOSE 8050\n",
        "CMD [\"python\", \"servidor_nucleo.py\"]\n",
        "\"\"\"\n",
        "with open('Dockerfile', 'w') as f:\n",
        "    f.write(dockerfile_content)\n",
        "\n",
        "# 3. Generar run_prod.sh (Script de lanzamiento Gunicorn)\n",
        "gunicorn_script = \"\"\"#!/bin/bash\n",
        "# Vitalis-Prime: Production Launch Script\n",
        "# --workers 4: Maneja 4 procesos concurrentes.\n",
        "# --bind 0.0.0.0:5000: Expone la API.\n",
        "# --timeout 120: Tiempo extendido para entrenamiento de la Red Neuronal.\n",
        "\n",
        "gunicorn --workers 4 --bind 0.0.0.0:5000 --timeout 120 servidor_nucleo:app\n",
        "\"\"\"\n",
        "with open('run_prod.sh', 'w') as f:\n",
        "    f.write(gunicorn_script)\n",
        "os.chmod('run_prod.sh', 0o755)\n",
        "\n",
        "print(\"✅ Infraestructura generada exitosamente:\")\n",
        "print(\"  - requirements.txt\")\n",
        "print(\"  - Dockerfile\")\n",
        "print(\"  - run_prod.sh (con permisos de ejecución 0o755)\")"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "deployment-guide"
      },
      "source": [
        "## 🚀 Guía de Despliegue en la Nube (Cloud Deployment)\n",
        "\n",
        "Una vez que tengas estos archivos en tu repositorio de GitHub, desplegarlos es un proceso de unos pocos clics.\n",
        "\n",
        "### Opción A: Render (Recomendado)\n",
        "1. Inicia sesión en [Render.com](https://render.com/).\n",
        "2. Haz clic en **New +** > **Web Service**.\n",
        "3. Conecta este repositorio de GitHub.\n",
        "4. **Runtime**: Selecciona `Docker` (Render detectará automáticamente el `Dockerfile` que generaste).\n",
        "5. **Variables de Entorno**: Agrega `PORT` = `5000`.\n",
        "6. Haz clic en **Deploy**.\n",
        "\n",
        "### Opción B: Railway\n",
        "1. Inicia sesión en [Railway.app](https://railway.app/).\n",
        "2. Haz clic en **New Project** > **Deploy from GitHub repo**.\n",
        "3. Selecciona tu repositorio.\n",
        "4. Railway detectará el contenedor y comenzará el proceso de *build* automáticamente.\n",
        "\n",
        "---\n",
        "**Comandos Rápidos para GitHub (Terminal Local):**\n",
        "```bash\n",
        "git init\n",
        "git add .\n",
        "git commit -m \"feat: Vitalis-Prime v1.0 Production Ready\"\n",
        "git branch -M main\n",
        "git remote add origin [https://github.com/TU_USUARIO/NOMBRE_REPO.git](https://github.com/TU_USUARIO/NOMBRE_REPO.git)\n",
        "git push -u origin main\n",
        "```"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
